version: '2.4'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile-20193
    restart: always
    ports:
      - 52773:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/iris/app